In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.metrics import confusion_matrix
from sklearn import model_selection
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
%matplotlib inline

In [2]:
digit= load_digits()
x=digit.data
y=digit.target

# Standardising the data

In [3]:
scaler= StandardScaler()
scaler.fit(x)
x=scaler.transform(x)

In [4]:
(x_train,x_test,y_train,y_test)=train_test_split(x,y,test_size=0.3,random_state=42)

#  PCA

In [5]:
from sklearn.decomposition import PCA

In [6]:
pca=PCA(n_components=15)
principal_compo=pca.fit_transform(x)
principal_df=pd.DataFrame(data=principal_compo)

# Logistic Regression

In [7]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
pred=model.predict(x_test)

# Score

In [9]:
model.score(x_test,y_test)

0.9648148148148148

# Confusion Matrix

In [10]:
matrix=confusion_matrix(y_test, pred)
print(matrix)

[[53  0  0  0  0  0  0  0  0  0]
 [ 0 46  2  0  0  0  0  0  2  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  1 51  0  0  0  0  2  0]
 [ 0  1  0  0 59  0  0  0  0  0]
 [ 0  0  0  0  0 64  1  0  0  1]
 [ 0  0  0  0  0  1 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  1  0  0  0  1  0  0 41  0]
 [ 0  0  0  1  0  1  0  0  3 54]]


# Classification Report

In [11]:
report=classification_report(y_test, pred)
print(report)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        53
          1       0.96      0.92      0.94        50
          2       0.94      1.00      0.97        47
          3       0.98      0.94      0.96        54
          4       1.00      0.98      0.99        60
          5       0.96      0.97      0.96        66
          6       0.98      0.98      0.98        53
          7       1.00      0.98      0.99        55
          8       0.85      0.95      0.90        43
          9       0.96      0.92      0.94        59

avg / total       0.97      0.96      0.97       540

