In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.metrics import confusion_matrix
from sklearn import model_selection
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.model_selection import train_test_split
%matplotlib inline

In [2]:
digit= load_digits()
x=digit.data
y=digit.target

In [3]:
x.shape, y.shape

((1797L, 64L), (1797L,))

In [4]:
(x_train,x_test,y_train,y_test)=train_test_split(x,y,test_size=0.3,random_state=42)

# 1. Gaussian kernel

In [5]:
model= SVC(kernel='rbf')

In [6]:
model.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
pred=model.predict(x_test)

# classification report

In [8]:
report=classification_report(y_test,pred)

C:\Users\rohit\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [9]:
print(report)

             precision    recall  f1-score   support

          0       1.00      0.40      0.57        53
          1       1.00      0.42      0.59        50
          2       1.00      0.55      0.71        47
          3       1.00      0.48      0.65        54
          4       1.00      0.25      0.40        60
          5       0.00      0.00      0.00        66
          6       1.00      0.66      0.80        53
          7       1.00      0.35      0.51        55
          8       0.12      1.00      0.21        43
          9       1.00      0.10      0.18        59

avg / total       0.81      0.39      0.45       540



# confusion matrix

In [10]:
matrix=confusion_matrix(y_test, pred)

In [11]:
print(matrix)

[[21  0  0  0  0  0  0  0 32  0]
 [ 0 21  0  0  0  0  0  0 29  0]
 [ 0  0 26  0  0  0  0  0 21  0]
 [ 0  0  0 26  0  0  0  0 28  0]
 [ 0  0  0  0 15  0  0  0 45  0]
 [ 0  0  0  0  0  0  0  0 66  0]
 [ 0  0  0  0  0  0 35  0 18  0]
 [ 0  0  0  0  0  0  0 19 36  0]
 [ 0  0  0  0  0  0  0  0 43  0]
 [ 0  0  0  0  0  0  0  0 53  6]]


In [12]:
model.score(x_test,y_test)

0.3925925925925926

In [13]:
metrics.accuracy_score(y_test,pred)

0.3925925925925926

# 2. Poly kernel

In [14]:
model2=SVC(kernel='poly')

In [15]:
model2.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
pred2=model2.predict(x_test)

# classfication report

In [17]:
report2=classification_report(y_test,pred2)

In [18]:
print(report2)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        53
          1       1.00      1.00      1.00        50
          2       1.00      1.00      1.00        47
          3       1.00      0.98      0.99        54
          4       1.00      1.00      1.00        60
          5       1.00      0.98      0.99        66
          6       1.00      1.00      1.00        53
          7       0.98      0.98      0.98        55
          8       0.95      0.98      0.97        43
          9       0.95      0.97      0.96        59

avg / total       0.99      0.99      0.99       540



# confusion matrix

In [19]:
matrix2=confusion_matrix(y_test, pred2)

In [20]:
print(matrix2)

[[53  0  0  0  0  0  0  0  0  0]
 [ 0 50  0  0  0  0  0  0  0  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 53  0  0  0  0  1  0]
 [ 0  0  0  0 60  0  0  0  0  0]
 [ 0  0  0  0  0 65  0  0  0  1]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  0  0  0  0  0  0  0 42  1]
 [ 0  0  0  0  0  0  0  1  1 57]]


In [21]:
metrics.accuracy_score(y_test,pred2)

0.9888888888888889

# 3. Linear kernel

In [22]:
model3=SVC(kernel='linear')

In [23]:
model3.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [24]:
pred3=model3.predict(x_test)

# classification report

In [25]:
report3=classification_report(y_test,pred3)

In [26]:
print(report3)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        53
          1       0.98      0.98      0.98        50
          2       0.98      1.00      0.99        47
          3       1.00      0.96      0.98        54
          4       0.98      0.98      0.98        60
          5       0.97      0.97      0.97        66
          6       1.00      1.00      1.00        53
          7       0.96      0.98      0.97        55
          8       0.95      0.98      0.97        43
          9       0.97      0.95      0.96        59

avg / total       0.98      0.98      0.98       540



# confusion matrix

In [27]:
matrix3=confusion_matrix(y_test, pred3)

In [28]:
print(matrix3)

[[53  0  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  1  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  1 52  0  1  0  0  0  0]
 [ 0  1  0  0 59  0  0  0  0  0]
 [ 0  0  0  0  0 64  0  1  0  1]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  0  0  0  0  1  0  0 42  0]
 [ 0  0  0  0  1  0  0  1  1 56]]


In [29]:
metrics.accuracy_score(y_test,pred3)

0.9796296296296296

# 4. Sigmoid kernel

In [30]:
model4=SVC(kernel='sigmoid')

In [31]:
model4.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
pred4=model4.predict(x_test)

# classification report

In [33]:
report4=classification_report(y_test,pred4)

In [34]:
print(report4)

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        53
          1       0.09      1.00      0.17        50
          2       0.00      0.00      0.00        47
          3       0.00      0.00      0.00        54
          4       0.00      0.00      0.00        60
          5       0.00      0.00      0.00        66
          6       0.00      0.00      0.00        53
          7       0.00      0.00      0.00        55
          8       0.00      0.00      0.00        43
          9       0.00      0.00      0.00        59

avg / total       0.01      0.09      0.02       540



# confusion matrix

In [35]:
matrix4=confusion_matrix(y_test, pred4)

In [36]:
print(matrix4)

[[ 0 53  0  0  0  0  0  0  0  0]
 [ 0 50  0  0  0  0  0  0  0  0]
 [ 0 47  0  0  0  0  0  0  0  0]
 [ 0 54  0  0  0  0  0  0  0  0]
 [ 0 60  0  0  0  0  0  0  0  0]
 [ 0 66  0  0  0  0  0  0  0  0]
 [ 0 53  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0 43  0  0  0  0  0  0  0  0]
 [ 0 59  0  0  0  0  0  0  0  0]]


In [37]:
metrics.accuracy_score(y_test,pred4)

0.09259259259259259