In [1]:
from sklearn import preprocessing 
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
from sklearn import model_selection
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
import seaborn as sns
import pandas as pd
import numpy as np
%matplotlib inline

# QUESTION 1

p(y/sunny)=p[(sunny/y)*p(y)]/p(sunny)

p(y/sunny)=[3/9*9/14]/5/14

p(y/sunny)=0.6

# QUESTION2

In [2]:
iris= load_iris()
x=iris.data
y=iris.target

In [3]:
x.shape, y.shape

((150L, 4L), (150L,))

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn import model_selection

In [6]:
(x_train,x_test,y_train,y_test)=train_test_split(x,y,test_size=0.3,random_state=42)

# GaussianNB

In [7]:
model=GaussianNB()

In [8]:
model.fit(x_train,y_train)

GaussianNB(priors=None)

In [9]:
pred=model.predict(x_test)

# Classification report

In [10]:
report=classification_report(y_test,pred)

In [11]:
print(report)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        19
          1       1.00      0.92      0.96        13
          2       0.93      1.00      0.96        13

avg / total       0.98      0.98      0.98        45



# Confusion matrix

In [12]:
matrix=confusion_matrix(y_test, pred)

In [13]:
print(matrix)

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [14]:
model.score(x_test,y_test)

0.9777777777777777

# MultinomialNB

In [15]:
model1=MultinomialNB()

In [16]:
model1.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [17]:
pred1=model1.predict(x_test)

# Classification report

In [18]:
report1=classification_report(y_test,pred)

In [19]:
print(report1)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        19
          1       1.00      0.92      0.96        13
          2       0.93      1.00      0.96        13

avg / total       0.98      0.98      0.98        45



# Confusion Matrix

In [20]:
matrix1=confusion_matrix(y_test, pred1)

In [21]:
print(matrix1)

[[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]


In [22]:
model1.score(x_test,y_test)

0.9555555555555556